version: '2.4'
services:
  epoc:
    image: projectbrain/brainbits:stable
    restart: always
    cpus: 0.5
    volumes:
     - socks:/var/socks
     - /dev:/dev
    device_cgroup_rules:
     - 'c *:* rmw'
    command: ['epoc.py']

  filtered:
    image: projectbrain/brainbits:stable
    restart: always
    volumes:
     - socks:/var/socks
    command: ['filtered.py']

  freqs:
    image: projectbrain/brainbits:stable
    restart: always
    volumes:
     - socks:/var/socks
    command: ['freqs.py']

  bands:
    image: projectbrain/brainbits:stable
    restart: always
    volumes:
     - socks:/var/socks
    command: ['bands.py']

  cells:
    image: projectbrain/braincells:classic
    restart: always
    volumes:
     - socks:/var/socks
    devices:
     - /dev/vchiq

volumes:
  socks:
